export const GET_TRADES_RESPONSE = 'GET_TRADES_RESPONSE';
export const GET_TRADE_RESPONSE = 'GET_TRADE_RESPONSE';
export const ADD_NEW_TRADE_RESPONSE = 'ADD_NEW_TRADE_RESPONSE';
export const UPDATE_EXISTING_TRADE_RESPONSE = 'UPDATE_EXISTING_TRADE_RESPONSE';
export const DELETE_TRADE_RESPONSE = 'DELETE_TRADE_RESPONSE';

export const GET_AUTHORS_RESPONSE = 'GET_AUTHORS_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
