spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bakisDB?useSSL=false
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # for remote access change server.address from localhost to 0.0.0.0
server:
  address: 0.0.0.0
  port: 8080

  # external APIs
api:
  edgar:
    feeds: [
      "https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&type=10-K,10-Q&start=0&count=100&output=atom"
    ]